<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

/**
 * Implements hook_theme().
 */
function qs_assistance_theme() {
  return [
    // Pages themes
    // ---------------------------------------------------------------------.
    'qs_assistance_collection_demands_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--assistance--collection-demands',
    ],
    'qs_assistance_collection_offers_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--assistance--collection-offers',
    ],
    // Blocks themes
    // ---------------------------------------------------------------------.
    'qs_assistance_demands_block' => [
      'variables' => ['variables' => []],
      'template' => 'qs--assistance--demands',
    ],
    'qs_assistance_offers_block' => [
      'variables' => ['variables' => []],
      'template' => 'qs--assistance--offers',
    ],
  ];
}
