services:
  # Drupal development server
  dev:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: docker-as-wait db:3306 -- docker-as-drupal apache-server
    depends_on:
      - db
      - mail
    environment:
      APP_ENV: development
      BASE_URL: http://localhost
      DATABASE_URL: mysql://drupal:drupal@db/drupal_development
      DEFAULT_CONTENT: qs_default_content
    restart: "no"
    volumes:
      - backups:/var/backups
      # Drupal
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./web/modules/custom:/var/www/web/modules/custom
      - ./web/sites/default/settings.development.php:/var/www/web/sites/default/settings.development.php
      # Theme
      - ./web/themes/quartiers_solidaires/templates:/var/www/web/themes/quartiers_solidaires/templates
      - ./web/themes/quartiers_solidaires/quartiers_solidaires.libraries.yml:/var/www/web/themes/quartiers_solidaires/quartiers_solidaires.libraries.yml
      - ./web/themes/quartiers_solidaires/quartiers_solidaires.info.yml:/var/www/web/themes/quartiers_solidaires/quartiers_solidaires.info.yml
      # Styleguide
      - ./package.json:/var/www/package.json
      - ./yarn.lock:/var/www/yarn.lock
      # Files
      - ./web/sites/default/files:/var/www/web/sites/default/files:delegated
      # Behat
      - ./behat:/var/www/behat
      - ./behat.yml:/var/www/behat.yml
      # Drush
      - ./web/sites/default/drush.development.yml:/var/www/drush/drush.yml

  # Drupal test server
  test:
    build:
      dockerfile: docker/Dockerfile
      context: .
    command: docker-as-wait db:3306 -- docker-as-drupal apache-server
    depends_on:
      - db
      - mail
      - browser
    environment:
      APP_ENV: test
      BASE_URL: http://localhost
      DATABASE_URL: mysql://drupal:drupal@db/drupal_test
      BEHAT_PROFILE: default
      TEST_DISABLE_MODULES: >-
        big_pipe
        honeypot
        captcha
        recaptcha
      DEFAULT_CONTENT: qs_default_content
    restart: "no"
    volumes:
      - backups:/var/backups
      # Drupal
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./web/modules/custom:/var/www/web/modules/custom
      # Styleguide
      - ./package.json:/var/www/package.json
      - ./yarn.lock:/var/www/yarn.lock
      # Behat
      - ./behat:/var/www/behat
      - ./behat.yml:/var/www/behat.yml
      # Drush
      - ./web/sites/default/drush.development.yml:/var/www/drush/drush.yml
    networks:
      default:
        aliases:
          # Hosts used in default content for testing
          - resoli.test

  # Test browser
  browser:
    image: seleniarm/standalone-chromium
    volumes:
      - /dev/shm:/dev/shm

  # Database
  db:
    image: mariadb:10.4
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal_%
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql

  # Mail
  mail:
    image: schickling/mailcatcher
    restart: unless-stopped

volumes:
  database:
  backups:
