label: 'Contenu récent'
description: 'Contenu récent.'
display:
  default:
    display_title: Master
    display_options:
      title: 'Contenu récent'
      exposed_form:
        options:
          submit_button: Anwenden
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      empty:
        area_text_custom:
          content: 'Kein Inhalt verfügbar.'
      use_more_text: Plus
  block_1:
    display_title: Bloc
