#!/bin/bash

# Kill runserver if one is alive
ps -ef | grep 'runserver' | grep -v grep | awk '{print $2}' | xargs kill -9

scriptDir=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )

echo "Running Behat"

BEHAT_DATABASE=$1

if [ "$BEHAT_DATABASE" = "" ]
then
  BEHAT_DATABASE="sqlite://localhost//tmp/portail_ca_behat.sqlite"
fi

cd $scriptDir

cd "../../"

composer install
bundle install
bundle exec cap staging styleguide:build_from_git

cd "web"

../vendor/bin/drush si standard --db-url=$BEHAT_DATABASE --site-name='Behat' --account-name=admin --account-pass=admin --account-mail=behat@antistatique.net -y
../vendor/bin/drush ev '\Drupal::entityManager()->getStorage("shortcut_set")->load("default")->delete();'
../vendor/bin/drush config-set system.site uuid "b38de9f3-fd4d-4779-ab7f-29e7b91556f1" -y
../vendor/bin/drush config-import -y --source='../config/d8/sync/'
../vendor/bin/drush updatedb -y
../vendor/bin/drush en qs_default_content -y
../vendor/bin/drush pmu hal serialization default_content qs_default_content -y
nohup bash -c "php ../vendor/bin/drush runserver &" && sleep 3;

cd ".."

set -e
BEHAT_PARAMS='{"gherkin" : {"cache" : null}}' ./vendor/bin/behat --colors --strict
behat_exit=$?

# Kill runserver if one is alive
ps -ef | grep 'runserver' | grep -v grep | awk '{print $2}' | xargs kill -9

exit $behat_exit
