<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

// Includes.
require_once 'inc/alias.inc';

/**
 * Implements hook_theme().
 */
function qs_activity_theme() {
  return [
    // Pages themes
    // ---------------------------------------------------------------------.
    'qs_activity_collection_by_theme_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--collection-by-theme',
    ],
    // Blocks themes
    // ---------------------------------------------------------------------.
    'qs_activity_events_collection_block' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--events-collection',
    ],
    'qs_activity_btn_activity_add_block' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--btn-activity-add',
    ],

  ];
}
