<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

// Includes.
require_once 'inc/alias.inc';

/**
 * Alter suggestions for fullpage.
 */
function qs_activity_theme_suggestions_page_alter(array &$suggestions, array &$variables) {
  // Set to fullpage layout some special pages.
  if (array_intersect($suggestions, [
    'page__activities__add',
    'page__events__add',
    'page__events__edit',
    'page__activities__dashboard__members',
  ])) {
    $suggestions[] = 'page__fullpage';
  }
  elseif (array_intersect($suggestions, [
    'page__activities__dashboard',
    'page__activities__edit',
    'page__activities__delete',
    'page__events__delete',
  ])) {
    $suggestions[] = 'page__fullmodal';
  }
}

/**
 * Implements hook_theme().
 */
function qs_activity_theme() {
  return [
    // Pages themes
    // ---------------------------------------------------------------------.
    'qs_activity_collection_by_theme_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--collection-by-theme',
    ],
    'qs_activity_collection_by_date_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--collection-by-date',
    ],
    'qs_activity_dashboard_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--dashboard',
    ],
    'qs_activity_event_dashboard_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--event-dashboard',
    ],
    'qs_activity_members_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--members',
    ],
    // Blocks themes
    // ---------------------------------------------------------------------.
    'qs_activity_events_collection_block' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--events-collection',
    ],
    'qs_activity_floating_actions_buttons_block' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--activity--floating-actions-buttons',
    ],

  ];
}
