<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Hook Entity Insert.
 *
 * Implements hook_entity_insert().
 *
 * Improve cache management by creating custom tag [entity]_list:[type]
 * Eg. node_list:news.
 */
function qs_site_entity_insert(EntityInterface $entity) {
  Drupal::service('cache_tags.invalidator')->invalidateTags([$entity->getEntityTypeId() . '_list:' . $entity->bundle()]);
}

/**
 * Hook Entity Update.
 *
 * Implements hook_entity_update().
 *
 * Improve cache management by creating custom tag [entity]_list:[type]
 * Eg. node_list:news.
 */
function qs_site_entity_update(EntityInterface $entity) {
  Drupal::service('cache_tags.invalidator')->invalidateTags([$entity->getEntityTypeId() . '_list:' . $entity->bundle()]);
}

/**
 * Hook Entity Delete.
 *
 * Implements hook_entity_delete().
 */
function qs_site_entity_delete(EntityInterface $entity) {
  Drupal::service('cache_tags.invalidator')->invalidateTags([$entity->getEntityTypeId() . '_list:' . $entity->bundle()]);
}

/**
 * Implements hook_theme_suggestions_hook_alter().
 *
 * Since Drupal 8.3.x, the 404 & 403 pages don't provide any suggestions.
 */
function qs_site_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $request = Drupal::service('request_stack')->getCurrentRequest();

  if (($request->attributes->get('exception') instanceof AccessDeniedHttpException)) {
    $suggestions[] = 'page__system__403';
  }

  if (($request->attributes->get('exception') instanceof NotFoundHttpException)) {
    $suggestions[] = 'page__system__404';
  }
}
