<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

/**
 * Implements hook_theme().
 */
function qs_community_theme() {
  return [
    // Pages themes
    // ---------------------------------------------------------------------.
    'qs_community_welcome_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--community--welcome',
    ],
    'qs_community_dashboard_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--community--dashboard',
    ],
    'qs_community_members_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--community--members',
    ],
    'qs_community_waiting_approval_page' => [
      'variables' => ['variables' => []],
      'template' => 'qs--community--waiting-approval',
    ],
    // Pages themes
    // ---------------------------------------------------------------------.
    'qs_community_welcome_floating_actions_buttons_block' => [
      'variables' => ['variables' => []],
      'template' => 'qs--community--welcome-floating-btn',
    ],
  ];
}
