<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_node_access().
 *
 * The administrative account (user ID #1) always passes any access check,
 * so this hook is not called in that case.
 */
function qs_acl_node_access(NodeInterface $node, $operation, AccountInterface $account) {
  $acl = \Drupal::service('qs_acl.access_control');

  if ($operation == 'view' && $node->bundle() == 'activity') {
    $community = $node->field_community->entity;
    if ($acl->hasAccessCommunity($community)) {
      return AccessResult::allowed();
    }

    return AccessResult::forbidden();
  }
}
