<?php

/**
 * @file
 * Legacy Drupal 7 code to implements hooks.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_access().
 *
 * The administrative account (user ID #1) always passes any access check,
 * so this hook is not called in that case.
 */
function qs_acl_node_access(NodeInterface $node, $operation, AccountInterface $account) {
  $acl = \Drupal::service('qs_acl.access_control');

  if ($operation == 'view' && $node->bundle() == 'activity') {
    $community = $node->field_community->entity;
    if ($acl->hasAccessCommunity($community)) {
      return AccessResult::allowed();
    }

    return AccessResult::forbidden();
  }
}

/**
 * Hook Community Entity Delete.
 *
 * Remove privilges of this community, to any user, when deleted.
 *
 * Implements hook_ENTITY_TYPE_delete().
 */
function qs_acl_taxonomy_term_delete(EntityInterface $entity) {
  /* @var \Drupal\Core\Entity\EntityTypeManagerInterface */
  $entityTypeManager = \Drupal::service('entity_type.manager');
  /* @var \Drupal\Core\Entity\ContentEntityStorageInterface */
  $privilegeStorage = $entityTypeManager->getStorage('privilege');
  /* @var \\Drupal\Core\Entity\Query\QueryInterface */
  $privilegeQuery = $privilegeStorage->getQuery();
}

/**
 * Hook Activity Entity Delete.
 *
 * Remove privilges of this activity, to any user, when deleted.
 *
 * Implements hook_ENTITY_TYPE_delete().
 */
function qs_acl_node_delete(EntityInterface $entity) {
}

/**
 * Hook User Entity Delete.
 *
 * Remove privilges of this User when deleted.
 *
 * Implements hook_ENTITY_TYPE_delete().
 */
function qs_acl_user_delete(EntityInterface $entity) {
}
