_core:
  default_config_hash: 0SeYZshzgoabDrbz-junYqeQOQ9BypPv2gaFcnqKy0M
langcode: fr
transport: smtp
smtp_host: in-v3.mailjet.com
smtp_port: 25
smtp_encryption: tls
sendmail_path: /usr/sbin/sendmail
sendmail_mode: bs
smtp_credential_provider: swiftmailer
smtp_credentials:
  swiftmailer:
    username: ''
    password: null
spool_directory: ''
smtp_username: ''
smtp_password: ''
