label: Fichiers
description: 'Trouver et gérer les fichiers.'
display:
  default:
    display_title: Maître
    display_options:
      title: Fichiers
      fields:
        fid:
          label: 'Identifiant (FID)'
        filename:
          label: Nom
        filemime:
          label: 'Type MIME'
        filesize:
          label: Taille
        status:
          label: Statut
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
      exposed_form:
        options:
          submit_button: Apply
      filters:
        filemime:
          expose:
            label: 'Type MIME'
        status:
          expose:
            label: Statut
  page_1:
    display_options:
      menu:
        title: Fichiers
  page_2:
    display_options:
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
