label: Personnes
description: 'Trouver et gérer les personnes interagissant avec votre site.'
display:
  default:
    display_title: Maître
    display_options:
      title: Personnes
      fields:
        user_bulk_form:
          label: 'Mise à jour en masse'
        name:
          label: "Nom d'utilisateur"
        status:
          label: Statut
          settings:
            format_custom_false: Blocked
            format_custom_true: Active
        roles_target_id:
          label: Roles
        created:
          label: 'Member for'
        access:
          label: 'Dernier accès'
        operations:
          label: Actions
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No people available.'
      filters:
        combine:
          expose:
            label: 'Name or email contains'
        status:
          group_info:
            label: Statut
            group_items:
              1:
                title: Active
              2:
                title: Blocked
        roles_target_id:
          expose:
            label: Role
        permission:
          expose:
            label: Permission
      use_more_text: more
  page_1:
    display_title: Page
    display_options:
      menu:
        title: List
        description: 'Trouver et gérer les personnes interagissant avec votre site.'
      tab_options:
        title: Personnes
        description: 'Manage user accounts, roles, and permissions.'
