label: "Page d'accueil"
description: "Tout le contenu promu en page d'accueil."
display:
  default:
    display_title: Maître
    display_options:
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
      empty:
        area_text_custom:
          content: 'No front page content has been created yet.'
        title:
          title: 'Welcome to [site:name]'
