label: 'Contenu récent'
description: 'Contenu récent.'
display:
  default:
    display_title: Maître
    display_options:
      title: 'Contenu récent'
      use_more_text: Plus
  block_1:
    display_title: Bloc
