label: Personnes
description: 'Trouver et gérer les personnes interagissant avec votre site.'
display:
  default:
    display_title: Maître
    display_options:
      title: Personnes
      fields:
        user_bulk_form:
          label: 'Mise à jour en masse'
        name:
          label: "Nom d'utilisateur"
        status:
          label: Statut
        access:
          label: 'Dernier accès'
        operations:
          label: Actions
      pager:
        options:
          tags:
            next: 'Next ›'
            previous: '‹ Previous'
            first: '« First'
            last: 'Last »'
      exposed_form:
        options:
          submit_button: Apply
      filters:
        status:
          group_info:
            label: Statut
  page_1:
    display_options:
      menu:
        description: 'Trouver et gérer les personnes interagissant avec votre site.'
      tab_options:
        title: Personnes
