<?php

/**
 * @file
 * QS Urls hooks.
 */

use Drupal\Core\Entity\EntityInterface;

require_once 'inc/helpers.inc';

// Includes.
require_once 'inc/activity.inc';

require_once 'inc/calendar.inc';

require_once 'inc/community.inc';

require_once 'inc/photo.inc';

require_once 'inc/subscription.inc';

/**
 * Implements hook_pathauto_alias_alter().
 *
 * Generate aliases & redirects based on node alias.
 */
function qs_urls_pathauto_alias_alter(&$alias, array &$context) {
  $moduleHandler = \Drupal::service('module_handler');

  if (isset($context['module'])
  && $context['module'] === 'taxonomy' && isset($context['data']['term'])) {

    // Uniquifier the alias, pathauto do it on the creation process, not here.
    // If we don't do it now, we will duplicate aliases/redirect
    // it may break the whole plateform.
    if ($context['op'] === 'insert') {
      $alias = qs_alias_uniquifier($context['data']['term'], $alias);
    }

    // Community.
    if ($moduleHandler->moduleExists('qs_community')) {
      qs_community_alias($context['data']['term'], $alias, $context['op']);
    }

    // Activity.
    if ($moduleHandler->moduleExists('qs_activity')) {
      qs_activity_alias($context['data']['term'], $alias, $context['op']);
      qs_activity_redirects($context['data']['term'], $alias, $context['op']);
    }

    // Calendar.
    if ($moduleHandler->moduleExists('qs_calendar')) {
      qs_calendar_alias($context['data']['term'], $alias, $context['op']);
      qs_calendar_redirects($context['data']['term'], $alias, $context['op']);
    }

    // Photo.
    if ($moduleHandler->moduleExists('qs_photo')) {
      qs_photo_alias($context['data']['term'], $alias, $context['op']);
      qs_photo_redirects($context['data']['term'], $alias, $context['op']);
    }

    // Subscription.
    if ($moduleHandler->moduleExists('qs_subscription')) {
      qs_subscription_alias($context['data']['term'], $alias, $context['op']);
    }
  }

  if (isset($context['module'])
  && $context['module'] === 'node' && isset($context['data']['node'])) {

    // Uniquifier the alias, pathauto do it on the creation process, not here.
    // If we don't do it now, we will duplicate aliases/redirect
    // it may break the whole plateform.
    if ($context['op'] === 'insert') {
      $alias = qs_alias_uniquifier($context['data']['node'], $alias);
    }

    // Activities.
    if ($moduleHandler->moduleExists('qs_activity')) {
      qs_activity_alias($context['data']['node'], $alias, $context['op']);
      qs_activity_redirects($context['data']['node'], $alias, $context['op']);
    }

    // Photo.
    if ($moduleHandler->moduleExists('qs_photo')) {
      qs_photo_alias($context['data']['node'], $alias, $context['op']);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Ensure deletion of aliases & redirects based on node.
 */
function qs_urls_node_delete(EntityInterface $entity) {
  $moduleHandler = \Drupal::service('module_handler');

  // Get the base alias of this node.
  $alias = $entity->toUrl()->toString();

  // Activities.
  if ($moduleHandler->moduleExists('qs_activity')) {
    qs_activity_alias($entity, $alias, 'delete');
    qs_activity_redirects($entity, $alias, 'delete');
  }

  // Photo.
  if ($moduleHandler->moduleExists('qs_photo')) {
    qs_photo_alias($entity, $alias, 'delete');
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * Ensure deletion of aliases & redirects based on taxonomy term.
 */
function qs_urls_taxonomy_term_delete(EntityInterface $entity) {
  $moduleHandler = \Drupal::service('module_handler');

  // Get the base alias of this term.
  $alias = $entity->toUrl()->toString();

  // Community.
  if ($moduleHandler->moduleExists('qs_community')) {
    qs_community_alias($entity, $alias, 'delete');
  }

  // Activity.
  if ($moduleHandler->moduleExists('qs_activity')) {
    qs_activity_alias($entity, $alias, 'delete');
    qs_activity_redirects($entity, $alias, 'delete');
  }

  // Calendar.
  if ($moduleHandler->moduleExists('qs_calendar')) {
    qs_calendar_alias($entity, $alias, 'delete');
    qs_calendar_redirects($entity, $alias, 'delete');
  }

  // Photo.
  if ($moduleHandler->moduleExists('qs_photo')) {
    qs_photo_alias($entity, $alias, 'delete');
    qs_photo_redirects($entity, $alias, 'delete');
  }

  // Subscription.
  if ($moduleHandler->moduleExists('qs_subscription')) {
    qs_subscription_alias($entity, $alias, 'delete');
  }
}
