<?php

namespace Drupal\qs_photo\Form;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CssCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Url;

/**
 * PhotoAddForm class.
 */
class AddForm extends FormBasic {

  /**
   * Name of dynamic fields generated by uppy once upload complete.
   *
   * This fields will contains the fid & uuid of every uploaded files.
   *
   * @var string
   */
  const UPPY_FILES = 'uppy_files';

  /**
   * Listing of allowed extensions.
   *
   * @var string
   */
  protected $extensions = 'png gif jpg jpeg';

  /**
   * Uppy locals strings.
   *
   * @var array
   */
  protected $uppyLocale = [];

  /**
   * Access Control Service.
   *
   * @var \Drupal\qs_acl\Service\AccessControl
   */
  protected $acl;

  /**
   * Activity Manager Service.
   *
   * @var \Drupal\qs_activity\Service\ActivityManager
   */
  protected $activityManager;

  /**
   * The current user account proxy.
   *
   * @var \Drupal\Core\Session\AccountInterface
   */
  protected $currentUser;

  /**
   * The node Storage.
   *
   * @var \Drupal\node\NodeStorageInterface
   */
  protected $nodeStorage;

  /**
   * The file Storage.
   *
   * @var \Drupal\file\FileStorageInterface
   */
  protected $fileStorage;

  /**
   * The image factory.
   *
   * @var \Drupal\Core\Image\ImageFactory
   */
  protected $imageFactory;

  /**
   * {@inheritdoc}
   */
  public function __construct(ContainerInterface $container) {
    // Initialize the container.
    parent::__construct($container);

    // From the container, inject services.
    $this->currentUser     = $this->getCurrentUser();
    $this->acl             = $this->getAcl();
    $this->nodeStorage     = $this->getNodeStorage();
    $this->fileStorage     = $this->getFileStorage();
    $this->activityManager = $this->getActivityManager();
    $this->imageFactory    = $this->getImageFactory();

    // Uppy locals strings.
    $this->uppyLocale = [
      'strings' => [
        'youCanOnlyUploadFileTypes' => $this->t('qs.uppy.can_only_upload_file_types'),
        // Used as the screen reader label for the plus (+) button that shows
        // the “Adding more files” screen.
        'addingMoreFiles' => $this->t('qs.uppy.adding_more_files'),
        // Used as the screen reader label for the plus (+) button that shows
        // the “Add more files” screen.
        'addMoreFiles' => $this->t('qs.uppy.add_more_files'),
        // When `inline: true`, used as the screen reader label for the
        // dashboard area.
        'dashboardTitle' => $this->t('qs.uppy.dashboard_title'),
        // Shown in the Informer when a link to a file was copied to
        // the clipboard.
        'copyLinkToClipboardSuccess' => $this->t('qs.uppy.copy_link_clipboard_success'),
        // Used when a link cannot be copied automatically - the user has to
        // select the text from the
        // input element below this string.
        'copyLinkToClipboardFallback' => $this->t('qs.uppy.copy_link_clipboard_fallback'),
        // Used as the hover title and screen reader label for buttons that
        // copy a file link.
        'copyLink' => $this->t('qs.uppy.copy_link'),
        // Used as the label for buttons that accept and close panels
        // (remote providers or metadata editor)
        'done' => $this->t('qs.uppy.done'),
        // Used as the screen reader label for buttons that remove a file.
        'removeFile' => $this->t('qs.uppy.remove_file'),
        // Used as the screen reader label for buttons that open the metadata
        // editor panel for a file.
        'editFile' => $this->t('qs.uppy.edit_file'),
        // Shown in the panel header for the metadata editor. Rendered as
        // "Editing image.png".
        'editing' => $this->t('qs.uppy.editing %{file}'),
        // Text for a button shown on the file preview, used to edit file
        // metadata.
        'edit' => $this->t('qs.uppy.edit'),
        // Used as the screen reader label for the button that saves metadata
        // edits and returns to the
        // file list view.
        'finishEditingFile' => $this->t('qs.uppy.finish_editing_file'),
        // Used as the label for the tab button that opens the system file
        // selection dialog.
        'myDevice' => $this->t('qs.uppy.my_device'),
        // Shown in the main dashboard area when no files have been selected,
        // and one or more remote provider plugins are in use. %{browse} is
        // replaced with a link that opens the system file selection dialog.
        'dropPasteImport' => $this->t('qs.uppy.drop_past_import %{browse}'),
        // Shown in the main dashboard area when no files have been selected,
        // and no provider plugins are in use. %{browse} is replaced with a
        // link that opens the system file selection dialog.
        'dropPaste' => $this->t('qs.uppy.drop_paste %{browse}'),
        // This string is clickable and opens the system file selection dialog.
        'browse' => $this->t('qs.uppy.browse'),
        // Used as the hover text and screen reader label for file progress
        // indicators when they have been fully uploaded.
        'uploadComplete' => $this->t('qs.uppy.upload_complete'),
        // Used as the hover text and screen reader label for the buttons to
        // resume paused uploads.
        'resumeUpload' => $this->t('qs.uppy.upload_resume'),
        // Used as the hover text and screen reader label for the buttons to
        // pause uploads.
        'pauseUpload' => $this->t('qs.uppy.upload_pause'),
        // Used as the hover text and screen reader label for the buttons to
        // retry failed uploads.
        'retryUpload' => $this->t('qs.uppy.upload_retry'),
        'back' => $this->t('qs.uppy.back'),

        // Used in a title, how many files are currently selected.
        'xFilesSelected' => [
          '0' => $this->t('qs.uppy.file_selected %{smart_count}'),
          '1' => $this->t('qs.uppy.files_selected %{smart_count}'),
        ],

        // @uppy/status-bar strings:
        // Shown in the status bar while files are being uploaded.
        'uploading' => $this->t('qs.uppy.uploading'),
        // Shown in the status bar once all files have been uploaded.
        'complete' => $this->t('qs.uppy.complete'),
        // Shown in the status bar if an upload failed.
        'uploadFailed' => $this->t('qs.uppy.upload_failed'),
        // Shown next to `uploadFailed`.
        'pleasePressRetry' => $this->t('qs.uppy.press_retry'),
        // Shown in the status bar while the upload is paused.
        'paused' => $this->t('qs.uppy.paused'),
        'error' => $this->t('qs.uppy.error'),
        // Used as the label for the button that retries an upload.
        'retry' => $this->t('qs.uppy.retry'),
        // Used as the label for the button that cancels an upload.
        'cancel' => $this->t('qs.uppy.cancel'),
        // Used as the screen reader label for the button that retries
        // an upload.
        'retryUpload' => $this->t('qs.uppy.retry_upload'),
        // Used as the screen reader label for the button that pauses an upload.
        'pauseUpload' => $this->t('qs.uppy.pause_upload'),
        // Used as the screen reader label for the button that resumes a
        // paused upload.
        'resumeUpload' => $this->t('qs.uppy.resume_upload'),
        // Used as the screen reader label for the button that cancels
        // an upload.
        'cancelUpload' => $this->t('qs.uppy_cancel_upload'),
        // When `showProgressDetails` is set, shows the number of files that
        // have been fully uploaded so far.
        'filesUploadedOfTotal' => [
          '0' => $this->t('qs.uppy.file_uploaded_of_total %{complete} %{smart_count}'),
          '1' => $this->t('qs.uppy.files_uploaded_of_total %{complete} %{smart_count}'),
        ],
        // When `showProgressDetails` is set, shows the amount of bytes that
        // have been uploaded so far.
        'dataUploadedOfTotal' => $this->t('qs.uppy.uploaded_of_total %{complete} %{total}'),
        // When `showProgressDetails` is set, shows an estimation of how long
        // the upload will take to complete.
        'xTimeLeft' => $this->t('qs.uppy.xtime_left %{time}'),
        // Used as the label for the button that starts an upload.
        'uploadXFiles' => [
          '0' => $this->t('qs.uppy.upload_file %{smart_count}'),
          '1' => $this->t('qs.uppy.upload_files %{smart_count}'),
        ],
        // Used as the label for the button that starts an upload, if
        // another upload has been started in the past and new files were
        // added later.
        'uploadXNewFiles' => [
          '0' => $this->t('qs.uppy.upload_new_file %{smart_count}'),
          '1' => $this->t('qs.uppy.upload_new_files %{smart_count}'),
        ],
        'uploadingXFiles' => [
          '0' => $this->t('qs.uppy.uploading_new_file %{smart_count}'),
          '1' => $this->t('qs.uppy.uploading_new_files %{smart_count}'),
        ],
        'youCanOnlyUploadX' => [
          '0' => $this->t('qs.uppy.can_only_upload_x_file %{smart_count}'),
          '1' => $this->t('qs.uppy.can_only_upload_x_files %{smart_count}'),
        ],
        'exceedsSize'    => $this->t('qs.uppy.exceeds_size'),
        'failedToUpload' => $this->t('qs.uppy.failed_to_upload %{file}'),
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'qs_photo_add_form';
  }

  /**
   * Checks access for add photos in the given community.
   *
   * @param \Drupal\Core\Session\AccountInterface $account
   *   Run access checks for this account.
   * @param \Drupal\taxonomy\TermInterface $community
   *   The community.
   *
   * @return \Drupal\Core\Access\AccessResultInterface
   *   The access result.
   */
  public function access(AccountInterface $account, TermInterface $community) {
    $access = AccessResult::forbidden();
    if ($this->acl->hasAccessCommunity($community)) {
      $access = AccessResult::allowed();
    }
    return $access;
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, TermInterface $community = NULL) {
    $form = parent::buildForm($form, $form_state);

    // Disable caching & HTML5 validation.
    $form['#cache']['max-age'] = 0;
    $form['#attributes']['theme'] = 'secondary';
    $form['#floating_buttons'][] = [
      'icon'   => 'plus',
      'label'  => $this->t('qs_photo.form.add.title'),
      'active' => TRUE,
    ];

    // Apply custom styles to wrapper.
    $form['#theme_wrappers'] = [
      'form__modal__multistep',
    ];

    $form['step-1'] = [
      '#type' => 'fieldset',
      '#description' => $this->t('qs_photo.add.form.step1.description'),
      '#attributes' => [
        'data-step' => $this->t('qs_photo.add.form.step1'),
      ],
      '#theme_wrappers' => [
        'container__center',
        'fieldset__step',
      ],
    ];

    if ($this->acl->hasBypass()) {
      // Show every activity in this community for bypass user.
      $nids = $this->activityManager->getThemed($community);
      $activities = $this->nodeStorage->loadMultiple($nids);
    }
    else {
      // Show only activity where user has access &
      // with at least one past event.
      $activities = $this->activityManager->getByUserPhoto($community, $this->currentUser);
    }

    $fallback = [];
    $select_options = [];
    foreach ($activities as $activity) {
      $fallback[$activity->id()] = $activity->getTitle();
      $select_options[] = [
        'nid'         => $activity->id(),
        'title'       => $activity->getTitle(),
      ];
    }

    $form['step-1']['activity'] = [
      '#title'     => $this->t('qs_photo.add.form.activity'),
      '#type'      => 'select',
      '#multiple'  => FALSE,
      '#required'  => FALSE,
      '#options'   => $fallback,
      '#validated' => TRUE,
      '#attributes'    => [
        'selectize'    => TRUE,
        'class'        => ['selectize-activity'],
        'data-options' => json_encode($select_options),
      ],
      '#theme_wrappers' => [
        'form_element',
        'container__center',
      ],
      '#ajax'     => [
        'callback' => [$this, 'selectEventAjax'],
      ],
    ];

    $form['step-2'] = [
      '#type' => 'fieldset',
      '#description' => $this->t('qs_photo.add.form.step2.description'),
      '#attributes' => [
        'data-step' => $this->t('qs_photo.add.form.step2'),
      ],
      '#theme_wrappers' => [
        'container__center',
        'fieldset__step',
      ],
    ];

    $form['step-2']['event'] = [
      '#title'     => $this->t('qs_photo.add.form.event'),
      '#type'      => 'select',
      '#required'  => FALSE,
      '#options'   => ['_none' => $this->t('qs.form.select')],
      '#validated' => TRUE,
      '#attributes'    => [
        'selectize'    => TRUE,
        'class'        => [
          'selectize-activity',
          'selectize-events',
        ],
        'data-sort-field' => '',
      ],
      '#theme_wrappers' => [
        'form_element',
        'container__center',
      ],
      '#ajax'     => [
        'callback' => [$this, 'showUppy'],
      ],
    ];

    $form['step-3'] = [
      '#type' => 'fieldset',
      '#description' =>
      $this->t('qs_photo.add.form.step3.description') .
      '<div class="text-center mb-3">' .
      $this->t('qs_photo.add.form.step3.helper @file_validate_extensions @file_validate_size @file_validate_image_resolution', [
        '@file_validate_extensions'       => $this->extensions,
        '@file_validate_size'             => $this->humanFilesize(file_upload_max_size()),
        '@file_validate_image_resolution' => '5000x5000',
      ]) .
      '</div>',
      '#attributes' => [
        'data-step' => $this->t('qs_photo.add.form.step3'),
      ],
      '#theme_wrappers' => [
        'container__center',
        'fieldset__step',
      ],
    ];

    $form['#attached']['library'][] = 'quartiers_solidaires/uppy';
    $form['step-3']['photos'] = [
      '#type'       => 'file',
      '#uppy'       => TRUE,
      '#multiple'   => TRUE,
      '#required'   => FALSE,
      '#hide'       => TRUE,
      '#data' => [
        'data-callback-fields'    => self::UPPY_FILES,
        'data-locale'             => json_encode($this->uppyLocale),
        'data-extensions'         => $this->extensions,
        'data-allowed-file-types' => json_encode($this->getMimeTypesFromExt($this->extensions)),
        'data-filesize'           => file_upload_max_size(),
        'data-upload-url'         => Url::fromRoute('qs_photo.file.upload')->toString(),
      ],
    ];

    $form['step-4'] = [
      '#type' => 'fieldset',
      '#description' => $this->t('qs_photo.add.form.step4.description'),
      '#attributes' => [
        'data-step' => $this->t('qs_photo.add.form.step4'),
        'class' => [
          'text-center',
        ],
      ],
      '#theme_wrappers' => [
        'container__center',
        'fieldset__step',
      ],
    ];

    $form['step-4']['publish'] = [
      '#type' => 'submit',
      '#name' => 'publish',
      '#value' => $this->t('qs_photo.add.form.publish'),
      '#attributes' => [
        'outline' => TRUE,
        'icon' => 'check',
        'icon_left' => TRUE,
        'class' => [
          'js-form-normal',
          'col-md-8',
          'mx-auto',
          'mb-3',
        ],
      ],
    ];

    $form['step-4']['comment'] = [
      '#type' => 'submit',
      '#name' => 'comment',
      '#value' => $this->t('qs_photo.add.form.comment'),
      '#attributes' => [
        'outline' => TRUE,
        'icon' => 'comment',
        'icon_left' => TRUE,
        'class' => [
          'js-form-normal',
          'col-md-8',
          'mx-auto',
          'mb-3',
        ],
      ],
    ];

    $form['step-4']['story'] = [
      '#type' => 'submit',
      '#name' => 'story',
      '#value' => $this->t('qs_photo.add.form.story'),
      '#attributes' => [
        'outline' => TRUE,
        'icon' => 'story',
        'icon_left' => TRUE,
        'onclick' => 'alert("Cette fonctionnalité n\'est pas encore disponible.");return false;',
        'class' => [
          'js-form-normal',
          'col-md-8',
          'mx-auto',
          'mb-3',
        ],
      ],
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    $event_nid = $form_state->getValue('event');
    $event = $this->getNodeStorage()->load($event_nid);
    $activity = NULL;

    // Detect illegal event or activity POST.
    if ($event && $event->bundle() === 'event') {
      $activity = $event->field_activity->entity;
    }
    else {
      $form_state->setErrorByName('[step-1][activity]', $this->t('qs.form.upload.illegal_choice'));
    }

    // Assert activity is filled.
    if (!$form_state->getValue('activity')) {
      $form_state->setErrorByName('[step-1][activity]', $this->t('qs.form.error.empty @fieldname', ['@fieldname' => $form['step-1']['activity']['#title']]));
    }

    // Assert event is filled.
    if (!$form_state->getValue('event')) {
      $form_state->setErrorByName('[step-2][event]', $this->t('qs.form.error.empty @fieldname', ['@fieldname' => $form['step-2']['event']['#title']]));
    }

    // Check write access of activity.
    if ($activity && $event
      && !$this->acl->hasWriteAccessPhoto($activity)) {
      $form_state->setErrorByName('[step-1][activity]', $this->t('qs.form.upload.illegal_choice'));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    // Get files field generated by javascript when upload is done from uppy.
    $files = $form_state->getUserInput()[self::UPPY_FILES];

    $event_nid = $form_state->getValue('event');
    $event = $this->getNodeStorage()->load($event_nid);
    $activity = $event->field_activity->entity;

    // Load FID as File.
    $photos = [];
    foreach ($files as $file_datas) {
      $data = json_decode($file_datas, TRUE);
      $photos[] = $this->fileStorage->load($data[0]['fid']);
    }

    // Create Node from File.
    $nodes = [];
    foreach ($photos as $photo) {
      $node = $this->getPhotoManager()->create($event, $photo);
      $nodes[] = $node->id();
    }

    drupal_set_message($this->t("qs_photo.form.add.success @number @event @activity", [
      '@activity' => $activity->getTitle(),
      '@event'    => $event->getTitle(),
      '@number'   => count($nodes),
    ]));

    $trigger = $form_state->getTriggeringElement();
    switch ($trigger['#name']) {
      case 'comment':
        $form_state->setRedirect('qs_photo.form.comments', [
          'activity' => $activity->id(),
          'photos'   => $nodes,
        ]);
        break;

      case 'story':
      case 'publish':
      default:
        $form_state->setRedirect('qs_photo.activity', ['activity' => $activity->id()]);
        break;
    }
  }

  /**
   * Called via Ajax to populate the Event field according Activity.
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   *
   * @return \Drupal\Core\Ajax\AjaxResponse
   *   The form model field structure.
   */
  public function selectEventAjax(array &$form, FormStateInterface $form_state) {
    $response = new AjaxResponse();

    $select_options[] = [
      'nid'   => '_none',
      'title' => $this->t('qs.form.select'),
    ];

    $activity_nid = $form_state->getValue('activity');

    if ($activity_nid) {

      $activity = $this->getNodeStorage()->load((int) $activity_nid);
      $events   = $this->getEventManager()->getAllPrev($activity);

      if ($events) {
        $select_options = [];
        foreach ($events as $event) {
          $select_options[] = [
            'nid'   => $event->id(),
            'title' => $event->field_end_at->date->format('d.m.Y') . ' - ' . $event->getTitle(),
          ];
        }
      }

      // Update the Step 2 description with activity name.
      $response->addCommand(new InvokeCommand('#qs-photo-add-form', 'updateStepDescription',
        [
          '#edit-step-2',
          $this->t('qs_photo.add.form.step2.description @activity',
            ['@activity' => $activity->getTitle()]),
        ]
      ));
    }

    $response->addCommand(new InvokeCommand('#edit-event', 'selectizeClearOptions'));
    $response->addCommand(new InvokeCommand('#edit-event', 'selectizeAddOptions', [$select_options]));
    return $response;
  }

  /**
   * Show the Upply uploader.
   *
   * @param array $form
   *   An associative array containing the structure of the form.
   * @param \Drupal\Core\Form\FormStateInterface $form_state
   *   The current state of the form.
   *
   * @return \Drupal\Core\Ajax\AjaxResponse
   *   The form model field structure.
   */
  public function showUppy(array &$form, FormStateInterface $form_state) {
    $response = new AjaxResponse();
    $response->addCommand(new CssCommand('#uppy-uploader-hidden', ['display' => 'block']));
    return $response;
  }

  /**
   * Get a human readable file size.
   *
   * @param int $bytes
   *   The original file size in bytes.
   * @param int $decimals
   *   The number of final decimals.
   *
   * @return string
   *   The human readable file size.
   */
  public function humanFilesize($bytes, $decimals = 2) {
    $size = ['o', 'ko', 'Mo', 'Go', 'To', 'Po', 'Eo', 'Zo', 'Yo'];
    $factor = floor((strlen($bytes) - 1) / 3);
    return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . ' [' . @$size[$factor] . ']';
  }

}
