name: Continuous Integration & Continuous Deployment
on: [ push ]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: cs2pr, composer:v2
      - uses: actions/checkout@v3
      - run: composer install --prefer-dist
      - run: ./vendor/bin/phpcs --report=checkstyle | cs2pr

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: phpstan, cs2pr, composer:v2
      - uses: actions/checkout@v3
      - run: composer install
      - run: ./vendor/bin/phpstan analyse ./web/modules/custom ./behat ./web/themes/quartiers_solidaires --error-format=checkstyle | cs2pr

  phpmd:
    name: phpmd
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: composer:v2
      - uses: actions/checkout@v3
      - run: composer install --prefer-dist
      - run: ./vendor/bin/phpmd ./web/modules/custom text ./phpmd.xml --suffixes php,module,inc,install,test,profile,theme,css,info,txt --exclude *Test.php
        continue-on-error: true
      - run: ./vendor/bin/phpmd ./behat text ./phpmd.xml --suffixes php

  php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: php-cs-fixer, cs2pr, composer:v2
      - uses: actions/checkout@v3
      - run: composer install --prefer-dist
      - run: ./vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

  upgrade-status:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg user=$(id -u) --build-arg group=$(id -g) test
          mkdir -p ./log ./backups
      - name: Run the docker stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d test browser
      - name: Bootstrap
        run: docker exec test docker-as-wait db:3306 -- docker-as-drupal bootstrap --force
      - name: Enable upgrade status
        run: docker-compose exec -T test docker-as-wait db:3306 -- ./vendor/bin/drush en upgrade_status -y
      - name: Run upgrade status
        run: docker-compose exec -T test docker-as-wait db:3306 -- /var/www/vendor/bin/drush upgrade_status:analyze --ignore-contrib --ignore-uninstalled --all

  build_docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerFile: Dockerfile
            image: quartiers-solidaires_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get the user id
        id: user_id
        run: |
          echo "::set-output name=id::$(id -u)"
      - name: Get the user group
        id: user_group
        run: |
          echo "::set-output name=id::$(id -g)"
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          pull: true
          build-args: |
            user=${{ steps.user_id.outputs.id }}
            group=${{ steps.user_group.outputs.id }}
          file: ${{ matrix.dockerFile }}
          tags: ${{ matrix.image }}:latest
          outputs: type=docker, dest=/tmp/${{ matrix.image }}.tar
          cache-from: type=gha,scope=${{ github.workflow }}_${{ matrix.image }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}_${{ matrix.image }}
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: /tmp/${{ matrix.image }}.tar
          key: ${{ runner.os }}-${{ matrix.image }}-${{ github.sha }}

  unit-tests:
    needs: build_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: /tmp/quartiers-solidaires_test.tar
          key: ${{ runner.os }}-quartiers-solidaires_test-${{ github.sha }}
      - name: Load Docker image
        run: docker load --input /tmp/quartiers-solidaires_test.tar
      - name: Up the docker-compose stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --no-build -d test
      - name: Run unit tests
        run: docker exec test docker-as-wait --mysql -- docker-as-drupal phpunit --skip-default-stops --group=quartier-solidaires

  functional-tests:
    needs: build_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: /tmp/quartiers-solidaires_test.tar
          key: ${{ runner.os }}-quartiers-solidaires_test-${{ github.sha }}
      - name: Load Docker image
        run: docker load --input /tmp/quartiers-solidaires_test.tar
      - name: Up the docker-compose stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --no-build -d test browser
      - name: Bootstrap
        run: docker exec test docker-as-wait --mysql -- docker-as-drupal bootstrap --install-only --force
      - name: Build Styleguide
        run: docker exec test yarn build --production
      # Build assets
      # Uncomment and set right node version if you have to build assets
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build Styleguide Library Node Autocomplete
        run: yarn && yarn build --production
        working-directory: ./web/themes/quartiers_solidaires/libs/node-autocomplete
      - name: Run Behat tests
        run: docker-compose exec -T test docker-as-wait --mysql test:8888 browser:4444 -- docker-as-drupal behat --user=www-data --skip-db-reset
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: ./app/logs

  deploy:
    name: Deploy
    needs: [phpmd, phpcs, phpstan, php-cs-fixer, unit-tests, functional-tests]
    if:
      contains('
      refs/heads/master
      refs/heads/dev
      ', github.ref)
    runs-on: ubuntu-latest
    env:
      PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - name: Set deployment environment variables based on Git branches
        working-directory: ./
        id: deploy_target
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              echo "::set-output name=DEPLOY_ENV::staging"
          fi
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
              echo "::set-output name=DEPLOY_ENV::production"
          fi
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '12'
      - name: Build Styleguide
        run: yarn && yarn build --production
      - name: Build Styleguide Library Node Autocomplete
        run: yarn && yarn build --production
        working-directory: ./web/themes/quartiers_solidaires/libs/node-autocomplete
      - name: Set Docker Image Tag
        id: image_tag
        run: echo "::set-output name=DOCKER_DEPLOY_IMAGE_TAG::resoli-deploy:$(date +%s)"
      - name: Pull Antistatique Deploy Docker Image
        run: docker pull antistatique/deploy
      - name: Build the docker image
        run: docker build --file docker/Dockerfile.deploy --tag ${{ steps.image_tag.outputs.DOCKER_DEPLOY_IMAGE_TAG }} .
      - name: Execute the deployment
        run: docker run  -v `pwd`/web/themes/quartiers_solidaires/:/app/web/themes/quartiers_solidaires/ --env CI --env PRIVATE_SSH_KEY --rm ${{ steps.image_tag.outputs.DOCKER_DEPLOY_IMAGE_TAG }} bundle exec cap ${{ steps.deploy_target.outputs.DEPLOY_ENV }} deploy
