name: CI
on: [ push ]

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: cs2pr, composer:v2
      - uses: actions/checkout@v4
      - run: composer install --prefer-dist
      - run: ./vendor/bin/phpcs --report=checkstyle | cs2pr

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: phpstan, cs2pr, composer:v2
      - uses: actions/checkout@v4
      - run: composer install
      - run: ./vendor/bin/phpstan analyse ./web/modules/custom ./behat ./web/themes/quartiers_solidaires --error-format=checkstyle | cs2pr

  php-deprecation-detector:
    name: php-deprecation-detector
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: psalm, composer:v2
      - uses: actions/checkout@v4
      - run: cd tools/php-deprecation-detector && composer install --prefer-dist
      # PHP 8.2 is not already supported by this tools:
      # @see https://github.com/wapmorgan/PhpDeprecationDetector/issues/73
      - run: ./tools/php-deprecation-detector/vendor/bin/phpdd --target 8.1 \
              --file-extensions php,module,inc,install,test,profile,theme,info \
              ./web/modules/custom
      - run: ./tools/php-deprecation-detector/vendor/bin/phpdd --target 8.1 --file-extensions php ./behat

  php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
          tools: php-cs-fixer, cs2pr, composer:v2
      - uses: actions/checkout@v4
      - run: cd tools/php-cs-fixer && composer install --prefer-dist
      - run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --using-cache=no --dry-run --format=checkstyle | cs2pr

  upgrade-status:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg user=$(id -u) --build-arg group=$(id -g) test
          mkdir -p ./log ./backups
      - name: Run the docker stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d test browser
      - name: Bootstrap
        run: docker exec test docker-as-wait db:3306 -- docker-as-drupal bootstrap --force
      - name: Enable upgrade status
        run: docker-compose exec -T test docker-as-wait db:3306 -- ./vendor/bin/drush en upgrade_status -y
      - name: Run upgrade status
        run: docker-compose exec -T test docker-as-wait db:3306 -- /var/www/vendor/bin/drush upgrade_status:analyze --ignore-contrib --ignore-uninstalled --all

  unit-tests:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg user=$(id -u) --build-arg group=$(id -g) test
          mkdir -p ./log ./backups
      - name: Run the docker stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d test
      - name: Run unit tests
        run: docker exec test docker-as-wait db:3306 -- docker-as-drupal phpunit --skip-default-stops

  behat-tests:
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build --build-arg user=$(id -u) --build-arg group=$(id -g) test
          mkdir -p ./log ./backups
      - name: Run the docker stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d test browser
      - name: Bootstrap
        run: docker exec test docker-as-wait db:3306 -- docker-as-drupal bootstrap --force --with-default-content
      - name: Run Behat tests
        run: docker-compose exec -T test docker-as-wait db:3306 test:80 browser:4444 -- docker-as-drupal behat --skip-db-reset --skip-default-content
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: ./log
