<?php

/**
 * @file
 * QS Subscription hooks.
 */

// Includes.
require_once 'inc/alias.inc';

/**
 * Implements hook_theme().
 */
function qs_subscription_theme() {
  return [
    'qs_subscription_subscribers_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--subscription--subscribers',
    ],
    'qs_subscription_waiting_approval_page' => [
      'variables' => ['variables' => []],
      'template'  => 'qs--subscription--waiting-approval',
    ],

  ];
}
